spring:
  config:
    activate:
      on-profile: rest
---
spring:
  config:
    activate:
      on-profile: rabbit
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672


queue:
  name: people
springdoc:
  api-docs:
    path: /docs
---

spring:
  config:
    activate:
      on-profile: kafka